trigger:
  - '*'

pool:
  vm-image: 'ubuntu-20.04'
  demands: 
   - npm

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNetSDK@2
  displayname: 'Use .Net SDK 6.x'
  inputs: 
   packagetype: 'SDK'
   version:   '6.x'

- task: npm@1
  displayname: 'Install nodejs'
  inputs: 
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayname: 'Run gulp tasks'

- script: 'echo "$(Build.BuildDefinitionName), $(Build.BuildId), $(BuildNumber)" > buildinfo.txt'
  displayname: 'Build Info for QA'
  workingdirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCli@2
  displayname: 'Restore Project Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    
- task: DotNetCoreCli@2
  displayname: 'Build Proejct - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
