trigger:
- '*'

pool:
  vmImage: ubuntu-latest

steps:
- bash: echo hello world

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world