parameters:
- name: myString
  displayName: Cliente
  type: string
  default:

trigger: none

jobs:
- job: build
  displayName: build
  pool:
    vmImage: ubuntu-latest
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.myString }} in commit $(BUILD.SOURCEVERSIONMESSAGE)

