trigger:
- main

pool: 
  vmImage: ubuntu-latest

variables:
  buldConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buldConfiguration)
  displayName: 'dotnet build $(buldConfiguration)'
