# ASP.NET CORE
# BUILD AND TEST ASP.NET CORE
trigger:
-mian

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayNmae: 'dotnet build $(buildConfiguration) '