trigger:
- main

pool:
  vmImage: Spacegame

  variables:
    buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
