# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- branch-pipeline

pool: 
  name: my-laptop 
  demands: 
   - npm
 
variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    verbose: true
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'

- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'