trigger:
- '*'

  # test
pool:
  vmImage: 'ubuntu-18.04'
  demands:
    - npm

variables:
  # solution: '**/*.sln'
  # buildPlatform: 'Any CPU'
  buildConfiguration: '$(buildConfiguration)'
  wwwrootDir: '$(wwwrootDir)'
  dotnetSdkVersion: 3.1.300
