# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# specifies that push to master branch cause a continuous integration build to run
trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  appname: 'OutYard Web'

steps:
# acquires a specific version of .NET Core (3.1)
- task: UseDotNet@2
  displayName: 'Use .NET Core 3.1 sdk'
  inputs:
    packageType: sdk
    version: '3.1.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
# installs a package, specified in package.json file and any packages that it depends on
- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

# compiles the application output    
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

  # writes information about the build to a file buildinfo.txt
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot