

trigger:
- main

pool: 
  vmImage: PROD-FACTORY

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build -- configuration $(buildConfiguration)
  displayname: 'dotnet build $(buildConfiguration)'
