### YamlMime:Yaml


trigger:
- '*'
pool:
  name: LocalPool
  demands:
  - agent.os -equals Linux  
  
variables:
  buildConfiguration: Release

steps:

- task: DotNetCoreCLI@2
  displayName: Restore project dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'
    
- task: DotNetCoreCLI@2
  displayName: Build the project - Release
  inputs:
    command: build
    arguments: --no-restore --configuration Release
    projects: '**/*.csproj'