
trigger:
 -main

pool:
vmImage: ubuntu-latest 

variables:
 buildConfiguration: 'Relese'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildconfiguration)'
