trigger:
  - '*'

pool:
    vmImage: 'ubuntu-latest'

        variables:
            buildConfiguration: 'Release'

            steps:
              - task: NodeTool@0 
                    inputs:
                            versionSpec: '16.x' # replace this value with the version that you need for your project
                                  displayName: 'Install Node.js'

              - task: UseDotNet@2
                  displayName: 'Use .NET SDK 5.x'
                      inputs:
                            packageType: sdk
                                  version: '5.x'

              - task: Npm@1
                  displayName: 'Run npm install'
                      inputs:
                            verbose: false

              - script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
                  displayName: 'Compile Sass assets'

              - task: gulp@1
                  displayName: 'Run gulp tasks'

              - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
                  displayName: 'Write build info'
                      workingDirectory: Tailspin.SpaceGame.Web/wwwroot

              - task: DotNetCoreCLI@2
                  displayName: 'Restore project dependencies'
                      inputs:
                            command: 'restore'
                                  projects: '**/*.csproj'

              - task: DotNetCoreCLI@2
                  displayName: 'Build the project - Release'
                      inputs:
                            command: 'build'
                                  arguments: '--no-restore --configuration Release'
                                        projects: '**/*.csproj'
