trigger:
- main

- job: Windows
  pool: PrimaryAgent


variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'donet build $(buildConfiguration)'