
trigger:
- main

pool:
    vmImage: ubuntu-latest

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfig)'
steps:
- bash: echo hello world