name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- '*'

pool: 'private'

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'  

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: Npm@1
  displayName: 'Install Node.js modules as defined in package.json'
  inputs:
    verbose: false

- task: CmdLine@2
  displayName: 'Compile Sass assets'
  inputs:
    script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'

- task: gulp@1
  displayName: 'Minify JavaScript and CSS files'
  inputs:
    targets: 
    enableCodeCoverage: false

- task: CmdLine@2
  displayName: 'Write build info'
  inputs:
    script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    workingDirectory: $(wwwrootDir) 

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
  
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
