parameters:
- name: myString
  displayName: Cliente
  type: string
  default:

trigger: none

steps:
  - task: TerraformInstaller@1
    displayName: install terraform
    inputs:
      terraformVersion: latest

  - task: TerraformCLI@0
    displayName: 'check terraform version'
    inputs:
      command: version

  - task: TerraformCLI@0
    displayName: 'terraform init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/cloudwatch'
    inputs:
      provider: 'aws'
      command: init
    env:
      AWS_ACCESS_KEY_ID: "$(AWS_ACCESS_KEY_ID)"
      AWS_SECRET_ACCESS_KEY: "$(AWS_SECRET_ACCESS_KEY)"

  - task: TerraformCLI@0
    displayName: 'terraform plan'
    inputs:
      command: plan
    env:
      AWS_ACCESS_KEY_ID: "$(AWS_ACCESS_KEY_ID)"
      AWS_SECRET_ACCESS_KEY: "$(AWS_SECRET_ACCESS_KEY)"



#jobs:
#- job: build
#  displayName: build
#  pool:
#    vmImage: ubuntu-latest
#  steps:
#  - script: echo building $(Build.BuildNumber) with ${{ parameters.myString }} in commit $(BUILD.SOURCEVERSIONMESSAGE)

