# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - "*"

pool:
  vmImage: "ubuntu-20.02"
  deamnds:
    - npm

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
  displayName: "Use .Net SDK 5.x"
  inputs:
    verbose: false
  
- task: Npm@1
  displayName: "Run npm install"

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: 'Compile node-sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.buildNumber)" > buildInfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCL@2
displayName: 'Restore project dependencies'
inputs:
  command: 'restore'
  projects: '**/*.csproj'


- task: DotNetCoreCL@2
  displayName: 'Build project -Release'
  inputs:
    command: 'build'
    argumenets: '--no-restore configuration Release'
    projects: '**/*.csproj'


  
  
