
trigger: 
- main 

pool: 
    name: default

variables:
    buildConfiguration: 'Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'b652b57d-8b56-4a8e-80ef-195b0b15a550'

steps:
- script:  dotnet build --configuration $(buildConfiguration)
    displayName:'dotnet build $(buildConfiguration)'
