# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
<<<<<<< HEAD
    - npm
=======
  - npm
>>>>>>> 9d95f7c50d996afc38d70e46c0518427d034b968

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'

steps:
- task: UseDotNet@2
<<<<<<< HEAD
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
=======
  displayName: 'Use .NET Core SDK 3.1.300'
  inputs:
    packageType: sdk
    version: 3.1.300
>>>>>>> 9d95f7c50d996afc38d70e46c0518427d034b968

- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

<<<<<<< HEAD
- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
=======
- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
>>>>>>> 9d95f7c50d996afc38d70e46c0518427d034b968
  displayName: 'Compile Sass assets'

- task: gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
<<<<<<< HEAD
  workingDirectory: $(wwwrootDir)
=======
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot
>>>>>>> 9d95f7c50d996afc38d70e46c0518427d034b968

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
<<<<<<< HEAD
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
  
=======
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
>>>>>>> 9d95f7c50d996afc38d70e46c0518427d034b968
