parameters:
- name: myString
  displayName: Cliente
  type: string
  default: nome do cliente

trigger: none

jobs:
- job: build
  displayName: build
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.mmyString }} in commit $(BUILD.SOURCEVERSIONMESSAGE)

