name:  $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)  

trigger:
- '*'

pool: 'private'

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'Install Node.js modules as defined in package.json'
  inputs:
    verbose: false

- task: CmdLine@2
  displayName: 'Compile Sass assets'
  inputs:
    script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'

- task: gulp@1
  displayName: 'Minify JavaScript and CSS files'
  inputs:
    targets: 
    enableCodeCoverage: false

- task: CmdLine@2
  displayName: 'Write build info'
  inputs:
    script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot  
- task: DotNetCoreCLI@2
  displayName: 'Install the latest .NET packages the app depends on.'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration  $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
