# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MyRunNumber: '1.0.0-CI-$(Build.BuildNumber)'

- task: Npm@1
  inputs:
    command: 'install'

- script: sass scss:css
  displayName: 'npm compile scss'

- task: gulp@1
  inputs:
    targets: 'run'
    enableCodeCoverage: false

- script: echo $(MyRunNumber) > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
- script: echo $(Build.BuildNumber) > Tailspin.SpaceGame.Web/wwwroot/buildinfo.txt
