trigger:
- main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

steps:
    - script: dotnet --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
