
trigger:
- main

pool:
  name: Default

variables:
  buildConfigurations: 'Release'


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build @(buildConfiguration)'