# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# specifies that push to master bracnh cause a continuous integration build to run
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  appname: 'OutYard Web'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build for $(appname) $(buildConfiguration)'
