trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Relese'

steps:
- script: dotnet build --configuration $(buildCOnfiguration)
  displayName: 'dotnet build $(buildConfiguration)'