trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Realese'
steps:
  - script: dotnet build --configuration $(buildConfiguration) 
    displayName: dotnet build --configuration
