pool:
  name: Default
steps:
- bash: echo hello world!!


stages:
  - stage: TerraformInstall
    displayName: "Terraform Install"
      - task: TerraformInstaller@1
          displayName: install terraform
            inputs:
              terraformVersion: latest