trigger:
- main

- job: Windows
  pool: PrimaryAgent
    vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'donet build $(buildConfiguration)'