# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
name: SecondPipeline 

trigger: none

# this pipeline will be triggered by another pipeline
resources:
  pipelines:
  - pipeline: previous-pipeline-trigger   # Name of the pipeline resource
    source: FunctionApp-icecream # Name of the pipeline referenced by the pipeline resource
   # project: Trigger-Pipeline-From-Another-Pipeline # Required only if the source pipeline is in another project
    trigger: true # enable the trigger

pool:
  vmImage: ubuntu-latest

steps:
  - script: echo This pipeline was set to be triggered after first pipeline completes.