# pool: MyAgentPool
# steps:
# - bash: echo hello world
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuraiotn  $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'