parameters:
- name: Imagem
  displayName: Pool Image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - ubuntu-latest
  - macOS-latest
  - jujubinha

parameters:
- name: Cliente
  displayName: Pool Image
  type: string




trigger: none

jobs:
- job: build
  displayName: build
  pool:
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building $(Build.BuildNumber) with ${{ parameters.image }} in commit $(BUILD.SOURCEVERSIONMESSAGE)