trigger:
- '*'

pool: dell

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '5.x'
  serviceName: 'DefaultService'

steps:
# - task: UseDotNet@2
#   displayName: 'Use .NET SDK $(dotnetSdkVersion)'
#   inputs:
#     packageType: sdk
#     version: '$(dotnetSdkVersion)'

# - task: Npm@1
#   displayName: 'Run npm install'
#   inputs:
#     verbose: false

# - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
#   displayName: 'Compile Sass assets'

# - task: gulp@1
#   displayName: 'Run gulp tasks'

# - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
#   displayName: 'Write build info'
#   workingDirectory: $(wwwrootDir)

# - task: DotNetCoreCLI@2
#   displayName: 'Restore project dependencies'
#   inputs:
#     command: 'restore'
#     projects: '**/*.csproj'

# - template: templates/build.yml
#   parameters:
#     buildConfiguration: 'Debug'

# - template: templates/build.yml
#   parameters:
#     buildConfiguration: 'Release'

# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'
#   condition: succeeded()

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(6ba70ef7-bab6-4b5d-99da-704d84831fa7)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az pipelines build tag add --build-id $(Build.BuildId) --tags service=$(serviceName)'