### YamlMime:Yaml


trigger:
- '*'
pool:
  name: LocalPool
  demands:
  - agent.os -equals Linux  
  
variables:
  buildConfiguration: Release

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'