pool:
  vmImage: 'Ubuntu-16.04'
  
steps:  
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)"'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot  
