pool:
  vmImage: 'Ubuntu-16.04'
  demands:
    - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '2.1.505'
  
#Display build info  
steps:  
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)"'
  displayName: 'Write build info'
  
#Config use of .NET Core SDK $(dotnetSdkVersion)
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: $(dotnetSdkVersion)

#Run npm install
- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false  

#Compile Sass assets
- script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
  displayName: 'Compile Sass assets'

#Run gulp tasks
- task: gulp@1
  displayName: 'Run gulp tasks'

#Send build info to file 'build-info.txt'
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > build-info.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

#Install, the project's dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'

#Publish the .zip file to Azure Pipelines
#succeeded() is the default condition, so you don't need to specify it
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()