parameters:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Build project artifacts for ${{ parameters.buildConfiguration }}"
    inputs:
      command: "build"
      arguments: "--no-restore --configuration ${{ parameters.buildConfiguration }}"
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    displayName: "Publish build artifacts- ${{ parameters.buildConfiguration }}"
    inputs:
      command: "publish"
      projects: "**/*.csproj"
      arguments: "--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}"
      zipAfterPublish: true
