# In a template file, use the parameters section instead of variables to define inputs.
parameters:
  buildConfiguration: 'Release'

steps:

# This task uses the DotNetCoreCLI@2 task to publish or package the app's build results (including its dependencies) into a folder. 
# The zipAfterPublish argument specifies to add the built results to a .zip file.
- task: DotNetCoreCLI@2
  displayName: 'Build the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration ${{ parameters.buildConfiguration }}'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish the project - ${{ parameters.buildConfiguration }}'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.buildConfiguration }}'
    zipAfterPublish: true