pool:
 vmImage:  'ubuntu-latest'
 demands: 'npm'

steps:
  - task: DotNetCoreInstaller@0
    displayName: 'installing dotnet core sdk 2.1.505'
    inputs:
      version: 2.1.505

  - task: Npm@1
    displayName: 'running npm install'
    inputs:
      verbose: false
  
  - script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
    displayName: 'compiling sass'

  - task: Gulp@1
    displayName: 'running gulp tasks'
  
  - script: 'echo "$(Build.BuildDefinitionName) $(Build.BuildId) $(Build.BuildNumber)" > buildinfo.txt'
    displayName: 'writing build info'
    workingDirectory: 'Tailspin.SpaceGame.Web/wwwroot'
  
  - task: DotNetCoreCLI@2
    displayName: 'restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'building project dependencies'
    inputs:
      command: 'build'
      arguments: '--no-restore --configuration Release'
      projects: '**/*.csproj'
  