stages:
    - stage: 'Training'
      displayName: 'setup server'
      jobs:
       - job: 'setupVm'
         variables:
           buildConfiguration: 'Release'
           SDKversion: '2.1.505'
           RootLocation: 'Tailspin.SpaceGame.Web/wwwroot'
         pool:
           vmImage: 'ubuntu-16.04'
           demands:
              - npm
         steps:
         - task: DotNetCoreInstaller@0
           displayName: 'Use .Net Core SDK $(SDKversion)'
           inputs:
             version: $(SDKversion)

         - task: Npm@1
           displayName: 'Run npm install'
           inputs:
             verbose: false

         - script: './node_modules/.bin/node-sass $(RootLocation) --output $(RootLocation)'
           displayName: 'Compile Sass assets'


         - task: gulp@1
           displayName: 'Run gulp tasks'

         - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
           displayName: 'Write build info'
           workingDirectory: $(RootLocation)
 
         - task: DotNetCoreCLI@2
           displayName: 'Restore project dependencies'
           inputs:
             command: 'restore'
             projects: '**/*.csproj'
 
         - template: templates/build.yml
           parameters:
             buildConfiguration: $(buildConfiguration)
    
         - task: PublishBuildArtifacts@1
           displayName: 'Publish Artifact: drop'
           condition: succeeded()