name: My First Action Demo
on: [push, pull_request]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm running"
      - run: echo "I completed my cycle"
      
 
      - name: 'Sending SMS Notification'
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: '+1(234)5678901'
          toPhoneNumber: '+1(234)3334444'
          message: 'Hello from Twilio' 
